packages:
  - .

catalog:
  '@chromatic-com/storybook': ^4.1.3
  '@commitlint/cli': ^20.2.0
  '@commitlint/config-conventional': ^20.2.0
  '@playwright/test': ^1.57.0
  '@secretlint/secretlint-rule-preset-recommend': ^11.2.5
  '@storybook/addon-a11y': ^10.1.10
  '@storybook/addon-designs': ^11.1.0
  '@storybook/addon-docs': ^10.1.10
  '@storybook/addon-mcp': ^0.1.6
  '@storybook/addon-onboarding': ^10.1.10
  '@storybook/addon-themes': ^10.1.10
  '@storybook/addon-vitest': ^10.1.10
  '@storybook/mdx2-csf': ^1.1.0
  '@storybook/nextjs': ^10.1.10
  '@storybook/test-runner': ^0.24.2
  '@stryker-mutator/core': ^9.4.0
  '@stryker-mutator/typescript-checker': ^9.4.0
  '@stryker-mutator/vitest-runner': ^9.4.0
  '@tailwindcss/postcss': ^4.1.18
  '@testing-library/dom': ^10.4.1
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.1
  '@testing-library/user-event': ^14.6.1
  '@textlint-ja/textlint-rule-preset-ai-writing': ^1.6.1
  '@textlint/textlint-plugin-markdown': ^15.5.0
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitest/coverage-v8': ^4.0.16
  '@vitest/ui': ^4.0.16
  dependency-cruiser: ^17.3.4
  eslint: ^9.39.2
  eslint-config-next: ^16.1.0
  jotai: ^2.16.0
  msw: ^2.12.4
  msw-storybook-addon: ^2.0.6
  next: ^16.1.0
  oxlint: ^1.34.0
  oxlint-tsgolint: ^0.10.0
  playwright-bdd: ^8.4.2
  prettier: ^3.7.4
  prettier-plugin-packagejson: ^2.5.20
  prettier-plugin-tailwindcss: ^0.7.2
  react: ^19.2.3
  react-dom: ^19.2.3
  remark: ^15.0.1
  remark-cli: ^12.0.1
  remark-frontmatter: ^5.0.0
  remark-gfm: ^4.0.1
  remark-lint: ^10.0.1
  remark-preset-lint-consistent: ^6.0.1
  remark-preset-lint-recommended: ^7.0.1
  remark-toc: ^9.0.0
  secretlint: ^11.2.5
  storybook: ^10.1.10
  tailwindcss: ^4.1.18
  textlint: ^15.5.0
  textlint-filter-rule-allowlist: ^4.0.0
  textlint-filter-rule-comments: ^1.2.2
  textlint-plugin-html: ^1.0.1
  textlint-rule-preset-ja-technical-writing: ^12.0.2
  typedoc: ^0.28.15
  typescript: ^5.9.3
  vitest: ^4.0.16
  zod: ^4.2.1

catalogMode: strict

cleanupUnusedCatalogs: true

disallowWorkspaceCycles: true

engineStrict: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@swc/core'
  - core-js-pure
  - esbuild

preferWorkspacePackages: true

saveWorkspaceProtocol: true

shamefullyHoist: false

sharedWorkspaceLockfile: true

strictPeerDependencies: true
