packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@axe-core/playwright": 4.11.0
  "@chromatic-com/storybook": 4.1.3
  "@commitlint/cli": 20.2.0
  "@commitlint/config-conventional": 20.2.0
  "@cyclonedx/cyclonedx-npm": 4.1.2
  "@eslint-community/eslint-plugin-eslint-comments": 4.5.0
  "@faker-js/faker": 10.1.0
  "@hookform/resolvers": 5.2.2
  "@netlify/vite-plugin-tanstack-start": 1.2.6
  "@ninoseki/eslint-plugin-neverthrow": 0.0.1
  "@pact-foundation/pact": 16.0.4
  "@playwright/test": 1.57.0
  "@radix-ui/react-label": 2.1.8
  "@radix-ui/react-radio-group": 1.3.8
  "@radix-ui/react-select": 2.2.6
  "@radix-ui/react-slider": 1.3.6
  "@radix-ui/react-slot": 1.2.4
  "@radix-ui/react-switch": 1.2.6
  "@secretlint/secretlint-rule-preset-recommend": 11.2.5
  "@storybook/addon-a11y": 10.1.11
  "@storybook/addon-designs": 11.1.0
  "@storybook/addon-docs": 10.1.11
  "@storybook/addon-mcp": 0.1.6
  "@storybook/addon-onboarding": 10.1.11
  "@storybook/addon-themes": 10.1.11
  "@storybook/addon-vitest": 10.1.11
  "@storybook/mdx2-csf": 1.1.0
  "@storybook/nextjs": 10.1.11
  "@storybook/nextjs-vite": 10.1.11
  "@storybook/test-runner": 0.24.2
  "@stryker-mutator/core": 9.4.0
  "@stryker-mutator/typescript-checker": 9.4.0
  "@stryker-mutator/vitest-runner": 9.4.0
  "@t3-oss/env-core": 0.13.10
  "@t3-oss/env-nextjs": 0.13.10
  "@tailwindcss/postcss": 4.1.18
  "@tailwindcss/vite": 4.1.18
  "@tanstack/devtools-vite": 0.4.0
  "@tanstack/eslint-config": 0.3.4
  "@tanstack/match-sorter-utils": 8.19.4
  "@tanstack/react-devtools": 0.9.0
  "@tanstack/react-form": 1.27.6
  "@tanstack/react-query": 5.90.15
  "@tanstack/react-query-devtools": 5.91.2
  "@tanstack/react-router": 1.144.0
  "@tanstack/react-router-devtools": 1.144.0
  "@tanstack/react-router-ssr-query": 1.144.0
  "@tanstack/react-start": 1.145.1
  "@tanstack/react-table": 8.21.3
  "@tanstack/router-plugin": 1.145.1
  "@testing-library/dom": 10.4.1
  "@testing-library/jest-dom": 6.9.1
  "@testing-library/react": 16.3.1
  "@testing-library/user-event": 14.6.1
  "@textlint-ja/textlint-rule-preset-ai-writing": 1.6.1
  "@textlint/textlint-plugin-markdown": 15.5.0
  "@trpc/client": 11.8.1
  "@trpc/server": 11.8.1
  "@trpc/tanstack-react-query": 11.8.1
  "@types/node": 25.0.3
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@vercel/analytics": 1.6.1
  "@vercel/speed-insights": 1.3.1
  "@vitejs/plugin-react": 5.1.2
  "@vitest/browser-playwright": 4.0.16
  "@vitest/coverage-v8": 4.0.16
  "@vitest/eslint-plugin": 1.6.4
  "@vitest/ui": 4.0.16
  babel-plugin-react-compiler: 1.0.0
  browserslist: 4.28.1
  chromatic: 13.3.4
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  concurrently: 9.2.1
  cspell: 9.4.0
  date-fns: 4.1.0
  dependency-cruiser: 17.3.5
  eslint: 9.39.2
  eslint-config-next: 16.1.1
  eslint-config-prettier: 10.1.8
  eslint-plugin-boundaries: 5.3.1
  eslint-plugin-functional: 9.0.2
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-jest-dom: 5.5.0
  eslint-plugin-jsdoc: 61.5.0
  eslint-plugin-jsx-a11y: 6.10.2
  eslint-plugin-n: 17.23.1
  eslint-plugin-playwright: 2.4.0
  eslint-plugin-promise: 7.2.1
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-react-refresh: 0.4.20
  eslint-plugin-regexp: 2.10.0
  eslint-plugin-security: 3.0.1
  eslint-plugin-sonarjs: 3.0.5
  eslint-plugin-storybook: 10.1.10
  eslint-plugin-strict-dependencies: 1.3.29
  eslint-plugin-testing-library: 7.15.3
  eslint-plugin-unicorn: 62.0.0
  eslint-plugin-unused-imports: 4.3.0
  fast-check: 4.5.2
  http-server: 14.1.1
  jiti: 2.6.1
  jotai: 2.16.1
  jsdom: 27.4.0
  knip: 5.78.0
  lefthook: 2.0.13
  lost-pixel: 3.22.0
  lucide-react: 0.562.0
  motion: 12.23.26
  msw: 2.12.7
  msw-storybook-addon: 2.0.6
  neverthrow: 8.2.0
  next: 16.1.1
  next-intl: 4.6.1
  next-safe-action: 8.0.11
  npm-run-all2: 8.0.4
  nuqs: 2.8.6
  oxlint: 1.36.0
  oxlint-tsgolint: 0.10.0
  pino: 10.1.0
  pino-pretty: 13.1.3
  playwright: 1.57.0
  playwright-bdd: 8.4.2
  prettier: 3.7.4
  prettier-plugin-packagejson: 2.5.20
  prettier-plugin-tailwindcss: 0.7.2
  react: 19.2.3
  react-dom: 19.2.3
  react-hook-form: 7.69.0
  reg-simple-keygen-plugin: 0.14.2
  reg-suit: 0.14.5
  remark: 15.0.1
  remark-cli: 12.0.1
  remark-frontmatter: 5.0.0
  remark-gfm: 4.0.1
  remark-lint: 10.0.1
  remark-preset-lint-consistent: 6.0.1
  remark-preset-lint-recommended: 7.0.1
  remark-toc: 9.0.0
  secretlint: 11.2.5
  storybook: 10.1.11
  storycap-testrun: 1.0.0
  stylelint: 16.26.1
  stylelint-config-standard: 39.0.1
  stylelint-config-tailwindcss: 1.0.0
  stylelint-declaration-strict-value: 1.10.11
  stylelint-high-performance-animation: 1.11.0
  stylelint-order: 7.0.1
  superjson: 2.2.6
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  textlint: 15.5.0
  textlint-filter-rule-allowlist: 4.0.0
  textlint-filter-rule-comments: 1.2.2
  textlint-plugin-html: 1.0.1
  textlint-rule-preset-ja-spacing: 2.4.3
  textlint-rule-preset-ja-technical-writing: 12.0.2
  textlint-rule-prh: 6.1.0
  ts-pattern: 5.9.0
  turbo: 2.7.2
  tw-animate-css: 1.4.0
  typedoc: 0.28.15
  typedoc-plugin-merge-modules: 7.0.0
  typedoc-theme-hierarchy: 6.0.0
  typescript: 5.9.3
  typescript-eslint: 8.50.1
  vite: 7.3.0
  vite-tsconfig-paths: 6.0.3
  vitest: 4.0.16
  wait-on: 9.0.3
  web-vitals: 5.1.0
  xstate: 5.25.0
  zod: 4.2.1

catalogMode: strict

cleanupUnusedCatalogs: true

disallowWorkspaceCycles: true

engineStrict: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - core-js-pure
  - esbuild
  - lefthook
  - msw
  - odiff-bin

preferWorkspacePackages: true

saveWorkspaceProtocol: true

shamefullyHoist: false

sharedWorkspaceLockfile: true

strictPeerDependencies: true
