packages:
  - .

catalog:
  "@chromatic-com/storybook": ^4.1.3
  "@commitlint/cli": ^20.2.0
  "@commitlint/config-conventional": ^20.2.0
  "@playwright/test": ^1.57.0
  "@secretlint/secretlint-rule-preset-recommend": ^11.2.5
  "@storybook/addon-a11y": ^10.1.10
  "@storybook/addon-designs": ^11.1.0
  "@storybook/addon-docs": ^10.1.10
  "@storybook/addon-mcp": ^0.1.6
  "@storybook/addon-onboarding": ^10.1.10
  "@storybook/addon-themes": ^10.1.10
  "@storybook/addon-vitest": ^10.1.10
  "@storybook/mdx2-csf": ^1.1.0
  "@storybook/nextjs": ^10.1.10
  "@storybook/nextjs-vite": ^10.1.10
  "@storybook/test-runner": ^0.24.2
  "@stryker-mutator/core": ^9.4.0
  "@stryker-mutator/typescript-checker": ^9.4.0
  "@stryker-mutator/vitest-runner": ^9.4.0
  "@tailwindcss/postcss": ^4.1.18
  "@testing-library/dom": ^10.4.1
  "@testing-library/jest-dom": ^6.9.1
  "@testing-library/react": ^16.3.1
  "@testing-library/user-event": ^14.6.1
  "@textlint-ja/textlint-rule-preset-ai-writing": ^1.6.1
  "@textlint/textlint-plugin-markdown": ^15.5.0
  "@types/node": ^25.0.3
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@vercel/analytics": ^1.6.1
  "@vercel/speed-insights": ^1.3.1
  "@vitest/browser-playwright": ^4.0.16
  "@vitest/coverage-v8": ^4.0.16
  "@vitest/eslint-plugin": ^1.5.4
  "@vitest/ui": ^4.0.16
  browserslist: ^4.28.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dependency-cruiser: ^17.3.4
  eslint: ^9.39.2
  eslint-config-next: ^16.1.0
  eslint-config-prettier: ^10.1.8
  "@eslint-community/eslint-plugin-eslint-comments": ^4.5.0
  eslint-plugin-boundaries: ^5.3.1
  eslint-plugin-functional: ^9.0.2
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^61.5.0
  eslint-plugin-n: ^17.23.1
  eslint-plugin-promise: ^7.2.1
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-security: ^3.0.1
  eslint-plugin-sonarjs: ^3.0.5
  eslint-plugin-storybook: ^10.1.10
  eslint-plugin-strict-dependencies: ^1.3.29
  eslint-plugin-testing-library: ^7.7.0
  eslint-plugin-unicorn: ^62.0.0
  eslint-plugin-unused-imports: ^4.3.0
  fast-check: ^4.5.0
  jotai: ^2.16.0
  lefthook: ^2.0.12
  lucide-react: ^0.562.0
  msw: ^2.12.4
  msw-storybook-addon: ^2.0.6
  next: ^16.1.0
  npm-run-all2: ^8.0.4
  oxlint: ^1.34.0
  oxlint-tsgolint: ^0.10.0
  playwright: ^1.57.0
  playwright-bdd: ^8.4.2
  prettier: ^3.7.4
  prettier-plugin-packagejson: ^2.5.20
  prettier-plugin-tailwindcss: ^0.7.2
  react: ^19.2.3
  react-dom: ^19.2.3
  reg-keygen-git-hash-plugin: ^0.14.5
  reg-notify-github-plugin: ^0.14.5
  reg-publish-s3-plugin: ^0.14.4
  reg-suit: ^0.14.5
  remark: ^15.0.1
  remark-cli: ^12.0.1
  remark-frontmatter: ^5.0.0
  remark-gfm: ^4.0.1
  remark-lint: ^10.0.1
  remark-preset-lint-consistent: ^6.0.1
  remark-preset-lint-recommended: ^7.0.1
  remark-toc: ^9.0.0
  secretlint: ^11.2.5
  storybook: ^10.1.10
  storycap-testrun: ^1.0.0
  stylelint: ^16.26.1
  stylelint-config-standard: ^39.0.1
  stylelint-config-tailwindcss: ^1.0.0
  stylelint-declaration-strict-value: ^1.10.11
  stylelint-high-performance-animation: ^1.11.0
  stylelint-order: ^7.0.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  textlint: ^15.5.0
  textlint-filter-rule-allowlist: ^4.0.0
  textlint-filter-rule-comments: ^1.2.2
  textlint-plugin-html: ^1.0.1
  textlint-rule-preset-ja-technical-writing: ^12.0.2
  tw-animate-css: ^1.4.0
  typedoc: ^0.28.15
  typedoc-plugin-merge-modules: ^7.0.0
  typedoc-theme-hierarchy: ^6.0.0
  typescript: ^5.9.3
  typescript-eslint: ^8.35.0
  vite: ^7.3.0
  vitest: ^4.0.16
  zod: ^4.2.1

catalogMode: strict

cleanupUnusedCatalogs: true

disallowWorkspaceCycles: true

engineStrict: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@swc/core"
  - core-js-pure
  - esbuild
  - lefthook

preferWorkspacePackages: true

saveWorkspaceProtocol: true

shamefullyHoist: false

sharedWorkspaceLockfile: true

strictPeerDependencies: true
